# Configuration file for the app.
#
#####################################################

dbUrl: jdbc:sqlite:src/main/resources/us-census.db
dbName: census_learn_sql
port: 8082
docRoot: webapp
displayedProperties: 100
columns: [age, class of worker, industry code, occupation code, education,
          wage per hour, last education, marital status, major industry code,
          major occupation code, mace, hispanice, sex, member of labor,
          reason for unemployment, fulltime, capital gain,
          capital loss, dividends, income tax liability,
          previous residence region, previous residence state, household-with-family,
          household-simple, weight, msa-change,
          reg-change, within-reg-change, lived-here,
          migration prev res in sunbelt, num persons worked for employer, family members under 118,
          father birth country, mother birth country, citizenship,
          own business or self employed, fill questionnaire for veteran's admin, veterans benefits,
          weeks worked in year, year, salary range]